/** Offline fallback when API is unreachable — keeps portals usable for demos */
const PARTNER_ID = 'partneruser';

const TODAY = new Date();
const fmtDate = (d) => d.toISOString().split('T')[0];
const dA = (n) => { let d = new Date(TODAY); d.setDate(d.getDate() - n); return fmtDate(d); };
const dL = (n) => fmtDate(new Date(TODAY.getTime() + n * 86400000));

export const CLIENT_DEMO = {
  users: [
    { username: 'masteruser', password: 'Test@2026', role: 'merchant', name: 'masteruser', walletBalance: 964.35 },
    { username: 'Test@isu', password: 'Test@2026', role: 'merchant', name: 'Test@isu', walletBalance: 12450.75 },
    { username: 'Test@Ad', password: 'Test@2027', role: 'admin', name: 'Krishna Das', walletBalance: 245800 },
    { username: 'partneruser', password: 'Test@2028', role: 'partner', name: 'Arjun Mehta (Partner)', walletBalance: 0, partnerId: PARTNER_ID }
  ],
  chargebacks: [
    { id: 'CB_PEND_3', caseId: 'CASE000993', userName: 'masteruser', rrn: '1234567812', txnId: '500003', txnDate: dA(10), createdDate: dA(2), respondByDate: dA(0), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 1500, adjAmt: 1500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend3_1', filename: 'Evidence_1.pdf', uploadedAt: '2026-06-01T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend3_2', filename: 'Evidence_2.pdf', uploadedAt: '2026-06-01T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend3_3', filename: 'Evidence_3.pdf', uploadedAt: '2026-06-01T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB_PEND_4', caseId: 'CASE000994', userName: 'Test@isu', rrn: '1234567813', txnId: '500004', txnDate: dA(12), createdDate: dA(1), respondByDate: dA(0), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 2500, adjAmt: 2500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend4_1', filename: 'Doc_A.pdf', uploadedAt: '2026-06-02T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend4_2', filename: 'Doc_B.pdf', uploadedAt: '2026-06-02T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend4_3', filename: 'Doc_C.pdf', uploadedAt: '2026-06-02T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB_PEND_5', caseId: 'CASE000995', userName: 'masteruser', rrn: '1234567814', txnId: '500005', txnDate: dA(15), createdDate: dA(3), respondByDate: dL(4), mStatus: 'Arbitration Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 3500, adjAmt: 3500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend5_1', filename: 'Receipt_copy.pdf', uploadedAt: '2026-06-03T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend5_2', filename: 'Terms.pdf', uploadedAt: '2026-06-03T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend5_3', filename: 'Invoice.pdf', uploadedAt: '2026-06-03T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB_PEND_6', caseId: 'CASE000996', userName: 'Test@isu', rrn: '1234567815', txnId: '500006', txnDate: dA(8), createdDate: dA(4), respondByDate: dL(5), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 4500, adjAmt: 4500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend6_1', filename: 'Customer_Comm.pdf', uploadedAt: '2026-06-04T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend6_2', filename: 'Shipping_Label.pdf', uploadedAt: '2026-06-04T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend6_3', filename: 'Tracking.pdf', uploadedAt: '2026-06-04T10:00:00Z', status: 'Pending Review' }] },

    { id: 'CB_PEND_1', caseId: 'CASE000991', userName: 'masteruser', rrn: '7788991122', txnId: '500001', txnDate: dA(14), createdDate: dA(5), respondByDate: dL(6), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 8500, adjAmt: 8500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend1_1', filename: 'DeliveryReceipt.pdf', uploadedAt: '2026-05-30T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend1_2', filename: 'StatementOfService.pdf', uploadedAt: '2026-05-30T10:00:00Z', status: 'Pending Review' }, { id: 'doc_pend1_3', filename: 'RefundInvoice.pdf', uploadedAt: '2026-05-30T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB_PEND_2', caseId: 'CASE000992', userName: 'Test@isu', rrn: '8899002233', txnId: '500002', txnDate: dA(10), createdDate: dA(6), respondByDate: dL(7), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 12000, adjAmt: 12000, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_pend2_1', filename: 'ServiceInvoice.pdf', uploadedAt: '2026-05-30T14:00:00Z', status: 'Pending Review' }, { id: 'doc_pend2_2', filename: 'ContractAgreement.pdf', uploadedAt: '2026-05-30T14:05:00Z', status: 'Pending Review' }, { id: 'doc_pend2_3', filename: 'DeliveryProof.pdf', uploadedAt: '2026-05-30T14:10:00Z', status: 'Pending Review' }] },
    { id: 'CB001', caseId: 'CASE000001', userName: 'masteruser', rrn: '6093156553', txnId: '8768987', txnDate: dA(6), createdDate: dA(2), respondByDate: dL(8), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback New', txnAmt: 1000, adjAmt: 1000, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB002', caseId: 'CASE000002', userName: 'masteruser', rrn: '6093152984', txnId: '8768988', txnDate: dA(7), createdDate: dA(3), respondByDate: dL(7), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback New', txnAmt: 3000, adjAmt: 3000, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB005', caseId: 'CASE000005', userName: 'masteruser', rrn: '6093152993', txnId: '8768991', txnDate: dA(5), createdDate: dA(0), respondByDate: dL(10), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 500, adjAmt: 500, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: true, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_4', filename: 'Evidence_1.pdf', uploadedAt: '2026-05-27T12:00:00Z', status: 'Pending Review' }, { id: 'doc_5', filename: 'Evidence_2.pdf', uploadedAt: '2026-05-27T12:00:00Z', status: 'Pending Review' }] },
    { id: 'CB024', caseId: 'CASE000024', userName: 'Test@isu', rrn: '1234567890', txnId: '100001', txnDate: dA(8), createdDate: dA(2), respondByDate: dL(5), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback New', txnAmt: 2000, adjAmt: 2000, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB033', caseId: 'CASE000033', userName: 'Test@isu', rrn: '9012345678', txnId: '300001', txnDate: dA(9), createdDate: dA(3), respondByDate: dL(6), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback New', txnAmt: 3200, adjAmt: 3200, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_VROL_01', caseId: 'CASE_VROL_01', userName: 'masteruser', rrn: '1231231231', txnId: '9898989', txnDate: dA(10), createdDate: dA(4), respondByDate: dL(3), mStatus: 'VROL Chargeback', mSubStatus: 'Chargeback New', txnAmt: 5000, adjAmt: 5000, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: true, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB101', caseId: 'CASE000101', userName: 'masteruser', rrn: '5566778890', txnId: '2233441', txnDate: dA(12), createdDate: dA(5), respondByDate: dL(9), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback Won', txnAmt: 4500, adjAmt: 4500, product: 'VISA', merchantAction: 'evidence', acquirerAction: 'accepted', visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_101', filename: 'Evidence_101.pdf', uploadedAt: '2026-06-01T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB102', caseId: 'CASE000102', userName: 'Test@isu', rrn: '1122334455', txnId: '8877665', txnDate: dA(15), createdDate: dA(6), respondByDate: dL(2), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback Lost', txnAmt: 1200, adjAmt: 1200, product: 'VISA', merchantAction: 'accepted', acquirerAction: 'accepted', visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB103', caseId: 'CASE000103', userName: 'masteruser', rrn: '9988776655', txnId: '5544332', txnDate: dA(16), createdDate: dA(3), respondByDate: dL(10), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 250, adjAmt: 250, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_103_1', filename: 'Evidence_103.pdf', uploadedAt: '2026-05-29T10:00:00Z', status: 'Pending Review' }, { id: 'doc_103_2', filename: 'Receipt_103.pdf', uploadedAt: '2026-05-29T10:05:00Z', status: 'Pending Review' }, { id: 'doc_103_3', filename: 'CommLog_103.pdf', uploadedAt: '2026-05-29T10:10:00Z', status: 'Pending Review' }] },
    { id: 'CB104', caseId: 'CASE000104', userName: 'Test@isu', rrn: '4455667788', txnId: '9900112', txnDate: dA(14), createdDate: dA(1), respondByDate: dL(12), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 800, adjAmt: 800, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB105', caseId: 'CASE000105', userName: 'masteruser', rrn: '2233445566', txnId: '6677889', txnDate: dA(20), createdDate: dA(10), respondByDate: dA(2), mStatus: 'Arbitration Raise', mSubStatus: 'Chargeback Won', txnAmt: 15000, adjAmt: 7500, product: 'VISA', merchantAction: 'evidence', acquirerAction: 'accepted', visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB106', caseId: 'CASE000106', userName: 'Test@isu', rrn: '7788990011', txnId: '3344556', txnDate: dA(22), createdDate: dA(12), respondByDate: dA(3), mStatus: 'Arbitration Raise', mSubStatus: 'Chargeback Lost', txnAmt: 6000, adjAmt: 6000, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB107', caseId: 'CASE000107', userName: 'masteruser', rrn: '1212121212', txnId: '4545454', txnDate: dA(11), createdDate: dA(2), respondByDate: dL(6), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 1800, adjAmt: 1800, product: 'VISA', merchantAction: 'evidence', acquirerAction: 'rejected', visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_107', filename: 'Evidence_107.pdf', uploadedAt: '2026-05-28T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB108', caseId: 'CASE000108', userName: 'masteruser', rrn: '3434343434', txnId: '5656565', txnDate: dA(12), createdDate: dA(3), respondByDate: dL(16), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 4200, adjAmt: 4200, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB109', caseId: 'CASE000109', userName: 'Test@isu', rrn: '8989898989', txnId: '2323232', txnDate: dA(10), createdDate: dA(3), respondByDate: dL(8), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 5600, adjAmt: 5600, product: 'VISA', merchantAction: 'evidence', acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_1', filename: 'Delivery_Proof.pdf', uploadedAt: '2026-05-28T10:00:00Z', status: 'Pending Review' }, { id: 'doc_2', filename: 'Statement_of_Service.pdf', uploadedAt: '2026-05-28T10:00:00Z', status: 'Pending Review' }, { id: 'doc_3', filename: 'Additional_Evidence.pdf', uploadedAt: '2026-05-28T10:00:00Z', status: 'Pending Review' }] },
    { id: 'CB110', caseId: 'CASE000110', userName: 'masteruser', rrn: '6767676767', txnId: '8989898', txnDate: dA(9), createdDate: dA(2), respondByDate: dL(2), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback Won', txnAmt: 900, adjAmt: 900, product: 'VISA', merchantAction: 'evidence', acquirerAction: 'accepted', visaPending: false, partnerId: PARTNER_ID, timeline: [], documents: [{ id: 'doc_110', filename: 'Evidence_110.pdf', uploadedAt: '2026-05-23T10:00:00Z', status: 'Pending Review' }] },
    
    { id: 'CB_GEN_201', caseId: 'CASE_GEN_201', userName: 'Test@isu', rrn: '998877201', txnId: 'TXN201', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Dispute Won Partially', txnAmt: 3010, adjAmt: 3010, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_202', caseId: 'CASE_GEN_202', userName: 'masteruser', rrn: '998877202', txnId: 'TXN202', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Dispute Won Fully', txnAmt: 3020, adjAmt: 3020, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_203', caseId: 'CASE_GEN_203', userName: 'Test@isu', rrn: '998877203', txnId: 'TXN203', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Dispute Lost – TAT Expired', txnAmt: 3030, adjAmt: 3030, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_204', caseId: 'CASE_GEN_204', userName: 'masteruser', rrn: '998877204', txnId: 'TXN204', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Dispute Lost – Accepted', txnAmt: 3040, adjAmt: 3040, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_205', caseId: 'CASE_GEN_205', userName: 'Test@isu', rrn: '998877205', txnId: 'TXN205', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Document Rejected', txnAmt: 3050, adjAmt: 3050, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_206', caseId: 'CASE_GEN_206', userName: 'masteruser', rrn: '998877206', txnId: 'TXN206', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 3060, adjAmt: 3060, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_207', caseId: 'CASE_GEN_207', userName: 'Test@isu', rrn: '998877207', txnId: 'TXN207', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Chargeback Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 3070, adjAmt: 3070, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_208', caseId: 'CASE_GEN_208', userName: 'masteruser', rrn: '998877208', txnId: 'TXN208', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Dispute Won Partially', txnAmt: 3080, adjAmt: 3080, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_209', caseId: 'CASE_GEN_209', userName: 'Test@isu', rrn: '998877209', txnId: 'TXN209', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Dispute Won Fully', txnAmt: 3090, adjAmt: 3090, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_210', caseId: 'CASE_GEN_210', userName: 'masteruser', rrn: '998877210', txnId: 'TXN210', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Dispute Lost – TAT Expired', txnAmt: 3100, adjAmt: 3100, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_211', caseId: 'CASE_GEN_211', userName: 'Test@isu', rrn: '998877211', txnId: 'TXN211', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Dispute Lost – Accepted', txnAmt: 3110, adjAmt: 3110, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_212', caseId: 'CASE_GEN_212', userName: 'masteruser', rrn: '998877212', txnId: 'TXN212', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Document Rejected', txnAmt: 3120, adjAmt: 3120, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_213', caseId: 'CASE_GEN_213', userName: 'Test@isu', rrn: '998877213', txnId: 'TXN213', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 3130, adjAmt: 3130, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_214', caseId: 'CASE_GEN_214', userName: 'masteruser', rrn: '998877214', txnId: 'TXN214', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Pre-Arbitration Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 3140, adjAmt: 3140, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_215', caseId: 'CASE_GEN_215', userName: 'Test@isu', rrn: '998877215', txnId: 'TXN215', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Dispute Won Partially', txnAmt: 3150, adjAmt: 3150, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_216', caseId: 'CASE_GEN_216', userName: 'masteruser', rrn: '998877216', txnId: 'TXN216', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Dispute Won Fully', txnAmt: 3160, adjAmt: 3160, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_217', caseId: 'CASE_GEN_217', userName: 'Test@isu', rrn: '998877217', txnId: 'TXN217', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Dispute Lost – TAT Expired', txnAmt: 3170, adjAmt: 3170, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_218', caseId: 'CASE_GEN_218', userName: 'masteruser', rrn: '998877218', txnId: 'TXN218', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Dispute Lost – Accepted', txnAmt: 3180, adjAmt: 3180, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_219', caseId: 'CASE_GEN_219', userName: 'Test@isu', rrn: '998877219', txnId: 'TXN219', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Document Rejected', txnAmt: 3190, adjAmt: 3190, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_220', caseId: 'CASE_GEN_220', userName: 'masteruser', rrn: '998877220', txnId: 'TXN220', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Chargeback In Progress', txnAmt: 3200, adjAmt: 3200, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_221', caseId: 'CASE_GEN_221', userName: 'Test@isu', rrn: '998877221', txnId: 'TXN221', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Retrieval Request', mSubStatus: 'Chargeback Resubmit', txnAmt: 3210, adjAmt: 3210, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_222', caseId: 'CASE_GEN_222', userName: 'masteruser', rrn: '998877222', txnId: 'TXN222', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Dispute Won Partially', txnAmt: 3220, adjAmt: 3220, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_223', caseId: 'CASE_GEN_223', userName: 'Test@isu', rrn: '998877223', txnId: 'TXN223', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Dispute Won Fully', txnAmt: 3230, adjAmt: 3230, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_224', caseId: 'CASE_GEN_224', userName: 'masteruser', rrn: '998877224', txnId: 'TXN224', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Dispute Lost – TAT Expired', txnAmt: 3240, adjAmt: 3240, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_225', caseId: 'CASE_GEN_225', userName: 'Test@isu', rrn: '998877225', txnId: 'TXN225', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Dispute Lost – Accepted', txnAmt: 3250, adjAmt: 3250, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_226', caseId: 'CASE_GEN_226', userName: 'masteruser', rrn: '998877226', txnId: 'TXN226', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Document Rejected', txnAmt: 3260, adjAmt: 3260, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_227', caseId: 'CASE_GEN_227', userName: 'Test@isu', rrn: '998877227', txnId: 'TXN227', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Chargeback In Progress', txnAmt: 3270, adjAmt: 3270, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] },
    { id: 'CB_GEN_228', caseId: 'CASE_GEN_228', userName: 'masteruser', rrn: '998877228', txnId: 'TXN228', txnDate: dA(6), createdDate: dA(1), respondByDate: dL(15), mStatus: 'Arbitration Raise', mSubStatus: 'Chargeback Resubmit', txnAmt: 3280, adjAmt: 3280, product: 'VISA', merchantAction: null, acquirerAction: null, visaPending: false, partnerId: PARTNER_ID, timeline: [] }
  ],
  ledger: [
    { id: 'ADJ101', merchant: 'masteruser', type: 'Debit', amount: 1000, date: dA(1), remarks: 'Lien hold — CB001' },
    { id: 'ADJ105', merchant: 'Test@isu', type: 'Debit', amount: 3200, date: dA(1), remarks: 'Lien hold — CB033' }
  ]
};
